[0m[[0minfo[0m] [0mRunning Main [0m
[0m[[0mdebug[0m] [0mWaiting for threads to exit or System.exit to be called.[0m
[0m[[0mdebug[0m] [0m  Classpath:[0m
[0m[[0mdebug[0m] [0m	/home/hady/Dropbox/UIC/Courses/CS-474-OOP/HW2/HW2/target/classes[0m
[0m[[0mdebug[0m] [0m	/home/hady/Dropbox/UIC/Courses/CS-474-OOP/HW2/HW2/lib/com.scitools.understand.plugin_1.1.3.jar[0m
[0m[[0mdebug[0m] [0m	/home/hady/.ivy2/cache/org.jgrapht/jgrapht-ext/jars/jgrapht-ext-1.0.0.jar[0m
[0m[[0mdebug[0m] [0m	/home/hady/.ivy2/cache/org.jgrapht/jgrapht-core/jars/jgrapht-core-1.0.0.jar[0m
[0m[[0mdebug[0m] [0m	/home/hady/.ivy2/cache/org.tinyjee.jgraphx/jgraphx/jars/jgraphx-2.0.0.1.jar[0m
[0m[[0mdebug[0m] [0m	/home/hady/.ivy2/cache/jgraph/jgraph/jars/jgraph-5.13.0.0.jar[0m
[0m[[0mdebug[0m] [0m	/home/hady/.ivy2/cache/org.antlr/antlr4-runtime/jars/antlr4-runtime-4.5.3.jar[0m
[0m[[0mdebug[0m] [0m	/home/hady/.ivy2/cache/org.jgrapht/jgrapht-demo/jars/jgrapht-demo-1.0.0.jar[0m
[0m[[0mdebug[0m] [0mWaiting for thread run-main-1 to terminate.[0m
[0m[[31merror[0m] [0m(run-main-1) java.lang.UnsatisfiedLinkError: Native Library /home/hady/Dropbox/UIC/Courses/CS-474-OOP/HW2/scitools/bin/linux64/Java/libUnderstand.so already loaded in another classloader[0m
java.lang.UnsatisfiedLinkError: Native Library /home/hady/Dropbox/UIC/Courses/CS-474-OOP/HW2/scitools/bin/linux64/Java/libUnderstand.so already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.scitools.understand.Understand.loadNativeLibrary(Understand.java:94)
	at com.scitools.understand.Understand.open(Understand.java:46)
	at ConnUnderstandDB.readUnderstandDB(ConnUnderstandDB.java:21)
	at Main.main(Main.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
[0m[[0mdebug[0m] [0m	Thread run-main-1 exited.[0m
[0m[[0mdebug[0m] [0mInterrupting remaining threads (should be all daemons).[0m
[0m[[0mdebug[0m] [0mSandboxed run complete..[0m
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2081)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2081)
	at scala.Option.foreach(Option.scala:236)
	at sbt.BuildCommon$class.toError(Defaults.scala:2081)
	at sbt.Defaults$.toError(Defaults.scala:39)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$38$$anonfun$apply$39.apply(Defaults.scala:750)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$38$$anonfun$apply$39.apply(Defaults.scala:748)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[0m[[31merror[0m] [0m(compile:[31mrun[0m) Nonzero exit code: 1[0m
